### ISSUE TITLE
hubot compatibility to mattermost

### ISSUE THREAD

**Issue by nildenrey** [hubotio/generator-hubot#100]
Hi,
I'm running mattermost version 4.8.0 on centos 7 server also I installed hubot to connect to mattermost.
I also completely run hubot help and its work on my terminal. But, I having trouble connecting it to mattermost. do you have any suggestion? Please help

**Comment by 3ch01c** [comment]
I recommend [hubot-matteruser](https://github.com/loafoe/hubot-matteruser) adapter.
