### ISSUE TITLE
Update yeoman-generator dependency to 0.18.10 or higher

### ISSUE THREAD

**Issue by dankingtech** [hubotio/generator-hubot#106]
Currently, this package uses a very outdated version of `yeoman-generator`, 0.17.0. That version contains a further dependency on an outdated version of `cheerio`, which depends on several outdated packages, which generate warnings such as the following:

```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated simple-bufferstream@0.0.4: no longer maintained
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

That dependency was removed in `yeoman-generator` version 0.18.10: https://github.com/yeoman/generator/commit/98f3ab1b7a7e225a88f485ee3cf5e21d45e66087#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

The current version is now 4.0.2. It may simply need a version bump, but at that much difference, it might also need some adjustments to the code as well. At least moving to version 0.18.10 should remove the warnings and potential issues.

**Comment by joeyguerra** [comment]
Done.
