### ISSUE TITLE
While Running hubot on nodejs cmd

### ISSUE THREAD

**Issue by kanusoni** [hubotio/generator-hubot#107]
when i am running this command \bin\hubot to run hubot i am getting error like this:-

ERROR Cannot load adapter Campfire - Error: Cannot find module 'hubot-Campfire'
Require stack:
- C:\Users\jarvis\node_modules\hubot\src\robot.js
- C:\Users\jarvis\node_modules\hubot\es2015.js
- C:\Users\jarvis\node_modules\hubot\index.js
- C:\Users\jarvis\node_modules\hubot\bin\hubot.js
- C:\Users\jarvis\node_modules\hubot\bin\hubot

could you please help me resolve this error. Thanks.

**Comment by joeyguerra** [comment]
`campfire.js` is lowercase. Have you tried running it via `bin/hubot -a campfire`?
