### ISSUE TITLE
Make heroku-keepalive optional

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/generator-hubot#25]
Suggested in https://github.com/github/hubot/issues/827 by @mal

> We have to run our Hubot on our own hardware due to security policy, unfortunately this means we get messages about missing Heroku URLs when starting up.
> 
> I've removed the plugin from the package.json and external-scripts.json but it would good to have it as an option at creation time.

**Comment by iancward** [comment]
@technicalpickles It looks like heroku-keepalive is still in the generator script: https://github.com/github/generator-hubot/blob/97746f1fe73df1aa00859c9a8c9ba5fd4fedae9e/generators/app/index.js#L139

**Comment by iancward** [comment]
Hi,
This is still an issue.

**Comment by iancward** [comment]
Hi,
This is still an issue.

**Comment by joeyguerra** [comment]
no longer a problem.
