### ISSUE TITLE
RFC; Promote coffee-script as peerDependency in scripts

### ISSUE THREAD

**Issue by mal** [hubotio/generator-hubot#33]
At present quite a lot of `hubot-*` plugins list one `coffee-script` version or another as a dependency. Of those, many are specifing the same version that `hubot` itself depends on, and thus it should only been needed for testing and should probably be in `devDependencies`.

Some scripts however require more recent versions of `coffee-script` for various reasons, by listing it in `peerDependencies` rather than `dependencies` we get the benefit of `npm` detecting conflicting scripts at install time rather than waiting for everything to explode when `bin/hubot` gets executed.

Given that `coffee-script` isn't in the script template's `_package.json` at all (and doesn't need to be) I'm not sure what the best approch here would be (assuming this all makes sense).

One possibility is porting #27 over to allow optionally specifing the `coffee-script` version at app creation time, at which point we have the generator write it into peerDependencies as part of the generation. The only problem I forsee with this is that it might not be apparent at creation time that a newer version than `1.6.3` might be required. To combat this a sane default for new scripts might be `^1.6.3`.

This could potentially lead to some weirdness where a `peerDependencies` conflict should have arisen but a package erroneously lists the version constraint as `^1.6.3` while in reality requiring a more recent minimum version. My hope is that with some clear documentation it should be a relatively trivial fix (update package.json so next time it will conflict and warn the end user about incompatible scripts at install time).

Hope all that makes some semblance of sense, look forward to hearing your thoughts!

**Comment by technicalpickles** [comment]
I think this is line with my thinking, thanks for putting it together! 

I had some concerns about peerDependencies is I've seen references to it going away, but I was just reading https://github.com/npm/npm/issues/6565 that it's less being deprecated, as the behavior being changed.

**Comment by mal** [comment]
Reading that, it sounds like the "correct" way to do this would be to end up with a tree that looks like this:

```
mybot@0.0.0 /home/mal/code/mybot
├─┬ hubot@2.11.1
│ └── dependencies (not coffee-script)
├─┬ hubot-example@1.1.0
│ └── dependencies (not coffee-script)
├─┬ hubot-wants-fresh-coffee@0.1.0
│ └── dependencies (not coffee-script)
└── coffee-script@1.7.1
```

package | dependency | peerDependency
--------|----------|------------
`mybot` | `coffee-script@*` | none
`hubot` | none | `coffee-script@^1.6.3`
`hubot-example` | none | `coffee-script@*`
`hubot-wants-fresh-coffee` | none | `coffee-script@1.7.x`

Which leaves the app to install `coffee-script` but the current version of `hubot` and the installed plugins restrict which version that is by adding their various requirements as `peerDependencies` such that the version that actually gets installed satisfies all parties.

I also brought over your suggestion from #27 about leaving the default `coffee-script` requirement as a wildcard, as that makes a lot of sense given that `hubot` and other more fussy plugins can then whittle that down into whatever they agree upon.

Obviously this would require changes to `hubot` in addition to the generator changes. A few scripts might require a small update to move from a direct dependency on `coffee-script` to a peerDependency, but my suspicion is that that number will be relatively low given that it doesn't seem to have been well known that it was possible to use a version above `1.6.3` until recently.

**Comment by mal** [comment]
It occurs to me that the wildcard could be problematic in certain situations; for instance:

1. Install plugin that uses `1.9.x` feature yet specifies wildcard
2. Install plugin that explicitly peerDepends on `1.7.x`

This would result in breaking the first plugin only when a correctly versioned legacy plugin was installed. I'm uncertain of the best way to catch this besides running tests against all coffee versions `^1.6.3` and up when the peerDependency is a wildcard and if any fail encouraging the author to correct it.

The problem with this is that it significantly raises the bar on getting into plugin writing. Indeed many current plugins lack tests and they may never have been run.

**Comment by mal** [comment]
After letting it stew for a while, it occured to me that all of this is only truely necessary if `hubot` continues to hard lock the `coffee-script` version. Without that lock all new and reinstalls of hubots would upgrade to the latest version of `coffee-script`. Since we'd keep the major version lock, this would avoid breaking changes (I know 1.9 had one, but it looks to be relatively minor, so long as they don't do it again).

Without breaking changes, any scripts (and indeed hubot itself) should "just work" on the latest version of coffee.

This would then re-orient this RFC toward whether `coffee-script` should be in the `devDependencies` of the script template for testing, or if it should simply remain ommited entirely.

---

As an aside, it feels weird that we didn't see this sooner, but it's also entirely possible my brain forgot the reason why the `hubot` lock on `coffee-script` can't be released ... :frowning:

**Comment by mal** [comment]
Have continued mulling this over and gone over the various threads on the topic again (#27, #6, github/hubot#863, github/hubot#770 and #11). I see two options based on the various suggestions and ideas put forward:

---

_NOTE:_ The `1.7.1` used below could be anything that matches `^1.7.0` (it simply has to be after the registration changed happened (1.7.0) to make life easy when running tests.

#### A

  1. `hubot` removes from explicit dependency on `coffee-script@1.6.3`
  2. `hubot` adds `coffee-script@^1.7.1` to `devDependencies` (for testing)
  3. `hubot` adds `coffee-script@^1.7.1` to `peerDependencies` (for running)
  4. generator `app` adds `coffee-script@*` to `dependencies` (`npm` v3 compat)
  5. generator `script` adds `coffee-script@^1.7.1` to `devDependencies` (for testing)
  6. generator `script` adds `coffee-script@^1.7.1` to `peerDependencies` (for running)

#### B
  1. `hubot` bumps lock from `coffee-script@1.6.3` to `coffee-script@^1.7.1`
  2. Leave the `app` generator as is; no dependency on `coffee-script`
  3. Add `coffee-script@^1.7.1` to `devDependencies` in the `script` generator

---

#### Pros (A)
  - It ensures only one version of `coffee-script` gets installed
  - It lets `npm` deal with finding common ground between hubot and plugins on which `coffee-script` to use.
  - It leverages `peerDependencies` correctly in an `npm` v3 world

#### Cons (A)
  - If a script requires a different version of `coffee-script` both dev and peer deps need updating...
    - ...but still only as bad as the current `hubot@2.x` dep

#### Pros (B)
  - Less changes

#### Cons (B)
  - Multiple versions of `coffee-script` installed
    - Last script to be installed gets it's version of `coffee-script` used (unpredictable, as current)
  - Not clear that `script` needs a non-dev dep adding to use a never version outside of tests

---

Both approaches will require that the version specified by `hubot` and the `script` generator stay in sync going forward, but I see no way to avoid that since new scripts should be testing against whatever hubot is currently requiring. However this should be palatable as the only reason I can forsee for another version change is a major bump of `coffee-script` which will require more work than just this anyway.

FWIW I personally much prefer A based upon the P&C lists.

**Comment by mal** [comment]
##### Secret Option C

Another option could be to alter the Gruntfile build/release process to precompile all `.coffee` files before pubishing to `npm`, this way everything would be plain old Javascript and we just bypass the whole `coffee-script`/`peerDependencies` nightmare.

**Comment by mal** [comment]
Given the feedback provided in npm/npm#7569 it would seem to me that **A** is the way to go. It offers the most flexibilty while ensuring compatability between hubot and installed scripts, and also that the version of `coffee-script` is idempotent (rather than just the version used by whatever script happens to be last in `package.json`).

@technicalpickles if that makes sense to you, I'd be happy to cook up some pull requests for the outlined changes?

**Comment by strugee** [comment]
This seems like a very bad idea. What exactly is wrong with having multiple CoffeeScript versions installed? Hubot modules should directly declare their dependencies in package.json instead of relying on an implicit global dependency in Hubot core - this'll only lead to version hell which npm is designed on purpose to prevent.

**Comment by strugee** [comment]
As a concrete example changes like #86 or even just bumping the `coffee-script` version - this will create all sorts of breakage outside of Hubot core, which is where it _should_ stay. See also http://module.party/

**Comment by technicalpickles** [comment]
There's nothing wrong per se with having multiple coffeescript versions _installed_. The problem is that at some point, one `coffee` executable is run:

- bin/hubot (generated from this repo) calls bin/hubot (from github/hubot)
- bin/hubot from github/hubot has `#!/usr/bin/env coffee`

hubot relies on coffee-script having been required, which makes it possible to `require` coffee files. Many hubot packages are just coffee script files, rather than transpiled javascript.

If there are incompatibilities with the version of coffee script you run in your instance of hubot, and a package you depend on that are .coffee rather than transpiled, then you are going to have problems. I believe that peerDependency at least solves that problem.

A better, longer term solution would be encouraging script  packages to transpile to javascript, but that is a bigger thing.

**Comment by strugee** [comment]
Ah right. That makes sense, thanks.

I guess this issue is more of a bandaid then - the long-term solution being getting module authors to transpile their stuff.
