### ISSUE TITLE
[Feature] Add 'Choose a License' to the template

### ISSUE THREAD

**Issue by stephenyeargin** [hubotio/generator-hubot#49]
By default, the generated module states `MIT` as the license in the `package.json` file. However, it does not include the license nor does it let you pick something else during setup.
- Include the MIT license by default (since it's stated in the package.json)
- Stretch goal: Add Yeoman step to select a license

**Comment by technicalpickles** [comment]
Are you talking about for the bot generator or the script generator?

Probably worth checking if there's any prior art for Yeoman licenses. A quick look lead me to https://github.com/jozefizso/generator-license for example.

**Comment by stephenyeargin** [comment]
I was concerned with the script generator (e.g. `yo hubot:script`), as most folks might not be as worried about their bot distribution.
