### ISSUE TITLE
Generating a custom repository url instead of the default one which has `hubot-scripts` organization name

### ISSUE THREAD

**Issue by sriharshakappala** [hubotio/generator-hubot#58]
generator-hubot by default is generating the repository url as `github.com/hubot-scripts/<my-hubot-script>`

Now that the [hubot-scripts](https://github.com/hubot-scripts) organization is deprecated and no longer accepting any packages, will it be a good idea to ask for username too and add it as a custom value in [_package.json](https://github.com/github/generator-hubot/blob/master/generators/script/templates/_package.json) file?

**Comment by technicalpickles** [comment]
That is a great point. At the least, we can stop making remote urls point at hubot-scripts, but I'm not sure the best way to handle the default remote url. Maybe leave it blank and let the user decide during the prompt?

**Comment by technicalpickles** [comment]
I started adding this, borrowing from generator-node. However, I'm running into some (unrelated) changes that are making it tough to test.

**Comment by stephenyeargin** [comment]
I think a sane default would be to use the `git.userName` variable. That's not going to be correct in the event they are planning to push to an organization, but it has a higher chance of being right than `hubot-scripts`.

**Comment by stephenyeargin** [comment]
Yeah, still should be addressed.

**Comment by joeyguerra** [comment]
the repository url is not in the package.json file.
