### ISSUE TITLE
hubot-scripts.json is deprecated

### ISSUE THREAD

**Issue by iancward** [hubotio/generator-hubot#75]
The generator script creates a hubot-scripts.json file, which is deprecated. It should be removed from the generator

https://github.com/github/generator-hubot/blob/97746f1fe73df1aa00859c9a8c9ba5fd4fedae9e/generators/app/index.js#L254

https://github.com/github/hubot/blob/498d65611388d2881e6ae24f74bd68a832a24211/bin/hubot#L110-L112

**Comment by iancward** [comment]
Hi,
This is still an issue.

**Comment by PadmaChannal** [comment]
I am facing the same problem. What might be the solution for this?
![image](https://user-images.githubusercontent.com/21287082/27550619-fede3832-5a65-11e7-9ba1-9fd65777df65.png)

**Comment by gr2m** [comment]
we already have a pull request that will resolve this issue at  https://github.com/hubotio/generator-hubot/pull/91. We hope to merge and release it soon :)
