### ISSUE TITLE
Consider replacing hubot-google-translate in generator

### ISSUE THREAD

**Issue by iancward** [hubotio/generator-hubot#76]
The latest release of hubot-translate (which is two years old) doesn't work due to changes in the Google Translate API, and that it appears that Google has started to charge for this service. Multiple issues and PRs have been opened against [the project](https://github.com/hubot-scripts/hubot-google-translate), and it appears abandoned. 
Maybe consider working with the maintainer(s) of hubot-google-translate or replacing the script in the default external-scripts.json with something that is a bit more recent and hopefully works? For example: https://github.com/kkpoon/hubot-microsoft-translator

**Comment by iancward** [comment]
Hi,
This is still an issue.

**Comment by technicalpickles** [comment]
Another option could be just removing this particular script. Ideally, the default set of script should just work without an extra configuration.

**Comment by iancward** [comment]
Greetings,
This is still an issue. Since this integration no longer works, it should probably be removed from the generator.

**Comment by mose** [comment]
The list of default plugins has been reduced during the migration from coffee to js and `hubot-google-translate` plugin is not included anymore.
