### ISSUE TITLE
Including scripts selectively

### ISSUE THREAD

**Issue by iangreenleaf** [hubotio/generator-hubot#83]
The README generated by this project suggests that you can only include some scripts from a package with the following `external-scripts.json`:

```json
{
  "hubot-fun": [
    "crazy",
    "thanks"
  ],
  "hubot-auto-deploy": "*"
}
```

However, trying this with the script package I just generated from this project, I am finding that I have to include the file extensions to get it to work:

```json
{
  "hubot-fun": [
    "crazy.coffee",
    "thanks.coffee"
  ],
  "hubot-auto-deploy": "*"
}
```

Seems like there are three possibilities:

1. Something is screwy with my install, and for other people it works without the extensions
2. We've stopped adding `.coffee` extensions to our script files and I missed that memo
3. This is generating wrong documentation or wrong `index.coffee`, and these two should be reconciled

**Comment by iangreenleaf** [comment]
@probot-stale[bot] awww, that would be a shame! This is a real issue, after all.

**Comment by iangreenleaf** [comment]
Well, that's too bad. I wish someone would take a look at this issue besides you, stalebot.

**Comment by iangreenleaf** [comment]
@stale hi!

**Comment by joeyguerra** [comment]
Have you tried recently? So much time has passed.
