### ISSUE TITLE
Hubot generator is generating package.json with old node

### ISSUE THREAD

**Issue by chriskol** [hubotio/generator-hubot#94]
Is the Hubot generator generating from the latest hubot release?  It looks like it's still pulling from an old release due to the file structure and files being different from the [hubot](https://github.com/hubotio/hubot) repo.  Specifically, it's referencing an old version of node which seems to be giving all sorts of warnings from Heroku.

**Comment by chriskol** [comment]
Apparently when I install from npm it's installing version 0.4, which is older than 0.3.1, which is somehow the latest release?

**Comment by mose** [comment]
Yeah it's currently in pre-release, the `@latest` is still the `hubot 2.x` version. You need to use the `@next` to get the `1.0.0` version.

See the warning on https://github.com/hubotio/generator-hubot/releases (I wonder where that `0.4` version is coming from, is it a typo).

**Comment by chriskol** [comment]
Yeah.  I'm not sure what's up but running `npm install -g yo generator-hubot` is pulling version 0.4, which I think actually predates 0.3.1 somehow.  It seems like it should actually be pulling 0.3.1?

**Comment by mose** [comment]
Ah I see. The `0.4.0` is from `2016-05-19` while `0.3.1` is from `2015-06-05`. but the 0.3.1 was flagged as 'latest'. Not sure why. But yes if you install without flag it will grab the `0.4.0`. The flag is just wrong.

**Comment by chriskol** [comment]
My understanding was that `0.4.0` is actually not the most recent version.  It says `0.3.1` was updated 15 days ago.  So the problem comes in that `0.3.1` I think is actually more recent than `0.4.0`.  This means it's pulling an outdated release is my understanding?  It should actually be pulling `0.3.1` as that appears to have been updated most recently?

On the other hand, maybe just the flag was updated 15 days ago?  The commits seem to indicate that `0.4.0` is indeed more up to date?  But like, as you said,... why switch `0.3.1` as the latest release?  

I don't know, I'm confused and installing from the pre-release version fixed it for me haha.  It would've been great to know about this when installing from the Hubot documentation though!

**Comment by mose** [comment]
Maybe @gr2m knows, he played with the flags. I would not be surprised that `0.3.1` was flagged `@latest` by mistake 15 days ago. Or maybe there is a reason, but I'm not aware.

**Comment by gr2m** [comment]
I think that was me by accident, looking into it

**Comment by gr2m** [comment]
not sure if someone fixed it already but latest is pointing to `0.4.0` now

```
$ npm info generator-hubot version
0.4.0
```

**Comment by chriskol** [comment]
Yeah.  It appears to be hitting it.  But running a curl for the latest release from ghithub DOES still give 0.3.1 fyi.

` curl -s https://api.github.com/repos/hubotio/generator-hubot/releases/latest`

**Comment by gr2m** [comment]
ah okay, that’s because I couldn’t find changelogs for 0.4, so I didn’t create a release for it. 

Can you explain why that would be a problem though? when you install the generator, it does not install it from GitHub but from npm

**Comment by gr2m** [comment]
I just created a release for 0.4 so that should also be no problem any longer

**Comment by chriskol** [comment]
Yeah I thought it was a problem at first because I was still getting heroku
security vulnerability warnings when using the hubot installation doc
instructive as this version of generator uses old node version. I went here
to investigate and saw 0.3.1 was more recently updated that 0.4 and made
the assumption 0.3.1 was actually more recent and was the release intended
for use. Hope that made sense. If not, no matter as it's fixed! :)
