### ISSUE TITLE
Yo hubot just hangs

### ISSUE THREAD

**Issue by lrosser** [hubotio/generator-hubot#99]
I am trying to setup Hubot for the first time. 

I run `npm install -g yo generator-hubot`
and get the following...

![image](https://user-images.githubusercontent.com/38354790/38740910-3fb0e56c-3efe-11e8-84a4-9f7125abf4ef.png)

then I run `yo hubot`

and it seems to hang at this point

![image](https://user-images.githubusercontent.com/38354790/38741061-a6b70e9e-3efe-11e8-994e-eddd7f7cd298.png)

Has anyone seen this before? Any ideas on what I am missing?

Thanks in advance for any help w/ this issue.

**Comment by joeyguerra** [comment]
Have you tried again lately? `hubot` was updated recently.
